services:
  tensorboard:
    image: tensorflow/tensorflow
    container_name: agarciaj/tensorboard
    volumes:
      - ../models/segformer_nu_formatted/runs:/runs
    ports:
      - 6006:6006
    user: "${UID}:${GID}"
    command: tensorboard --logdir /runs --port 6006 --bind_all
    restart: on-failure:10
    healthcheck:
      test: curl --fail -s http://localhost:6006 || exit 1
      interval: 60s
      timeout: 6s
      retries: 3
      start_period: 30s