services:
  tensorboard:
    image: tensorflow/tensorflow
    container_name: agarciaj_tensorboard
    volumes:
      - ../models/segformer_nu_formatted/runs:/raw2seg_bev
      - ../models/segformer_bev/runs:/raw2bev_seg
    ports:
      - 6006:6006
    user: "${UID}:${GID}"
    command: tensorboard --logdir_spec=raw2bev_seg:/raw2bev_seg,raw2seg_bev:/raw2seg_bev --port 6006 --bind_all
    restart: on-failure:10
    healthcheck:
      test: curl --fail -s http://localhost:6006 || exit 1
      interval: 60s
      timeout: 6s
      retries: 3
      start_period: 30s