[data]
type = "BEVDataset" # [NuImages, BEVDataset] 
dataroot = "./tmp/BEVDataset"
testing = true      # if set, the 'mini' version of the dataset 
                    # will be taken as trainig and evaluation sets

[model]
output_path = "./tmp/models"
model_name = "model1"
pretrained = "nvidia/mit-b0"

[training]
batch_size = 32
epochs = 10
learning_rate = 0.001
weight_decay = 0
