[data]
type = "BEVDataset" # [NuImages, BEVDataset] 
dataroot = "/dataset"
testing = false     # if set, the 'mini' version of the dataset 
                    # will be taken as trainig and evaluation sets

[model]
output_path = "/models"
model_name = "segformer_bev"
pretrained = "nvidia/mit-b2"

[training]
batch_size = 16
epochs = 100
learning_rate = 0.01
weight_decay = 0.001
ls_steps = 100 # Logging/Saving steps
dataloader_num_workers = 4      # (optional)
val_acc_steps = 32              # (optional)
resume_from_checkpoint = false