[data]
type = "NuImages" # [NuImages, BEVDataset] 
dataroot = "./tmp/NuImages"
testing = true     # if set, the 'mini' version of the dataset 
                    # will be taken as trainig and evaluation sets

[model]
output_path = "./models"
model_name = "segformer_nu_test"
pretrained = "nvidia/mit-b0"

[training]
batch_size = 4
epochs = 100
learning_rate = 0.001
weight_decay = 0
ls_steps = 5        # Logging/Saving steps
# val_acc_steps = 32  # (optional)
